// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/learning/progress': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learning/progress.get').default>>>>
    }
    '/api/learning/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/learning/submit.post').default>>>>
    }
    '/api/llm/translate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/llm/translate.post').default>>>>
    }
    '/api/vocabulary/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vocabulary/add.post').default>>>>
    }
    '/api/vocabulary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vocabulary/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}