// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/5/2025, 2:36:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/roy/eng_read/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/plugins/**/*.{js,ts,mjs}","/home/roy/eng_read/composables/**/*.{js,ts,mjs}","/home/roy/eng_read/utils/**/*.{js,ts,mjs}","/home/roy/eng_read/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/roy/eng_read/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;